branches:
    only:
      - /.*/

language: rust

git:
    quiet: true

os:
    - linux
    - osx

arch:
    - amd64
    - arm64

before_script:
    - env

script:
    - if [ "x$TRAVIS_LANGUAGE" = "xrust" ]; then
          if [ "x$TRAVIS_OS_NAME" = "xwindows" ]; then
              rustup set default-host x86_64-pc-windows-msvc;
              export ML=-nologo;
          fi;
          (cd bindings/rust; cargo test --release)
      fi
    - if which go > /dev/null 2>&1; then
          (cd bindings/go; go test -test.v)
      fi

matrix:
    include:
      - os: windows
        language: rust
        rust: stable-msvc
      - os: windows
        language: go
      - os: linux
        arch: arm64
        language: go

notifications:
    email: false

before_cache:
    - if [ "x$TRAVIS_LANGUAGE" = "xrust" ]; then
          (cd bindings/rust;
           cargo clean -p blst; cargo clean -p blst --release;
           rm -rf target/.rustc_info.json;
           rm -rf target/{debug,release}/*/blst-*;
           rm -rf target/{debug,release}/incremental;
           rm -rf target/{debug,release}/build/src;
           rm -rf target/{debug,release}/build/build)
      fi
    - (cd "$TRAVIS_HOME"; rm -rf .cargo/registry/src)
    - (cd "$TRAVIS_HOME"; rm -rf .cargo/registry/index/*/.cache)

cache:
    cargo: true
    directories:
      - bindings/rust/target

